// Regenerates the "Threat actors linked to Malaysia" table in
// content/my-threat-landscape/threat-actor.md (between the ACTOR-TABLE markers)
// from Threat Watch entries whose MISP galaxy targets include Malaysia.
//
//   node scripts/actor-table.mjs
import { readdirSync, readFileSync, writeFileSync } from "fs"
import { join } from "path"

const THREATS = "content/my-threat-landscape/threats"
const PAGE = "content/my-threat-landscape/threat-actor.md"
const START = "<!-- ACTOR-TABLE:START (generated by scripts/actor-table.mjs) -->"
const END = "<!-- ACTOR-TABLE:END -->"

// Suspected origin as reported by vendors/governments; mirrors the clustering in the
// flowchart above. Actors without a well-established attribution are left as "—".
const ORIGIN = {
  China: [
    "UNC3886", "APT15", "APT23", "APT27", "APT30", "APT40", "APT41", "Earth-Estries", "Earth-Lusca",
    "Earth-Longzhi", "Earth-Alux", "RedJuliett", "RedDelta", "HAFNIUM", "GALLIUM", "PLATINUM",
    "Hellsing", "Naikon", "LOTUS-PANDA", "GOBLIN-PANDA", "Evasive-Panda", "Aoqin-Dragon", "TA428",
    "Worok", "MUSTANG-PANDA", "SharpPanda", "Storm-2077", "GhostEmperor", "Unfading-Sea-Haze",
  ],
  Iran: ["Fox-Kitten", "MuddyWater", "OilRig", "APT35", "APT42", "Cyber-Av3ngers"],
  Russia: ["APT28", "APT29"],
  "North Korea": ["Lazarus-Group"],
  India: ["RAZOR-TIGER", "QUILTED-TIGER", "HAZY-TIGER"],
  "South Korea": ["DarkHotel"],
  USA: ["Equation-Group"],
  Indonesia: ["INDOHAXSEC-TEAM"],
}
const originOf = (actor) =>
  Object.entries(ORIGIN).find(([, list]) => list.some((a) => a.toLowerCase() === actor.toLowerCase()))?.[0] ?? "—"

const actors = new Map()
for (const file of readdirSync(THREATS)) {
  if (!/^[0-9a-f-]{36}\.md$/.test(file)) continue
  const text = readFileSync(join(THREATS, file), "utf8")
  const title = text.match(/^title:\s*(.*)$/m)?.[1] ?? ""
  const date = text.match(/^date:\s*(\S+)/m)?.[1] ?? ""
  const targetsMalaysia = text.includes('target-information="Malaysia"') || /malaysia/i.test(title)
  if (!targetsMalaysia) continue
  for (const [, raw] of text.matchAll(/threat-actor=\s*"?#?([^"\n]+)"?/g)) {
    const actor = raw.trim()
    if (/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(actor)) continue // unresolved galaxy UUIDs
    const list = actors.get(actor) ?? []
    list.push({ date, title: title.replace(/^\d{4}-\d{2}-\d{2}\s+/, ""), slug: file.slice(0, -3) })
    actors.set(actor, list)
  }
}

const rows = [...actors.entries()]
  .map(([actor, entries]) => {
    entries.sort((a, b) => b.date.localeCompare(a.date))
    return { actor, entries, latest: entries[0] }
  })
  .sort((a, b) => b.entries.length - a.entries.length || b.latest.date.localeCompare(a.latest.date))

const esc = (s) => s.replace(/\|/g, "\\|").replace(/\[|\]/g, "")
const table = [
  START,
  "",
  `*${rows.length} actors across Threat Watch entries whose targets include Malaysia. Generated ${new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Kuala_Lumpur" })}.*`,
  "",
  "| Threat actor | Suspected origin (as reported) | Entries | Most recent entry |",
  "| --- | --- | --- | --- |",
  ...rows.map(
    ({ actor, entries, latest }) =>
      `| [[tags/${actor.toLowerCase()}\\|${actor.replace(/-/g, " ")}]] | ${originOf(actor)} | ${entries.length} | ${latest.date}: [[my-threat-landscape/threats/${latest.slug}\\|${esc(latest.title).slice(0, 80)}]] |`,
  ),
  "",
  END,
].join("\n")

const page = readFileSync(PAGE, "utf8")
const crlf = page.includes("\r\n")
const normalized = page.replace(/\r\n/g, "\n")
if (!normalized.includes(START) || !normalized.includes(END)) {
  console.error(`Markers not found in ${PAGE}`)
  process.exit(1)
}
const updated =
  normalized.slice(0, normalized.indexOf(START)) + table + normalized.slice(normalized.indexOf(END) + END.length)
writeFileSync(PAGE, crlf ? updated.replace(/\n/g, "\r\n") : updated)
console.log(`✅ Actor table updated: ${rows.length} actors`)
